travel_time_network:
  epochs: 1000
  lr: 0.00075
  n_hidden_1: 5
  n_hidden_2: 5
  n_output: 1
  device_type: 'cpu'
  train_batch_size: 16000
  test_batch_size: 1
  network_width: 40
delay_network:
  epochs: 1
  lr: 0.001
  #n_feature: 9
  n_hidden_1: 4
  n_hidden_2: 4
  n_output: 1
  device_type: 'cpu'
  train_batch_size: 64
  test_batch_size: 1
  network_width: 10
class_network:
  lr: 0.001
  epochs: 10
  device_type: 'cpu'
  train_batch_size: 128
  test_batch_size: 1
  network_width: 96
k_nearest_neighbour:
  n_neighbors: 6
  weights: 'uniform'
