version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s %(levelname)s %(name)s %(message)s"
handlers:
    log_handler:
        class: logger.log_handler.LogHandler
        level: INFO
        fname: logger/logs/data_engine
        formatter: simple
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
root:
    level: DEBUG
    handlers: [console, log_handler]